local STRINGS = GLOBAL.STRINGS

------------------RECIPE STRINGS-----------------
-----Unnamed Garden
STRINGS.NAMES.FOUNTAIN_WEREPIG = "Werepig Fountain"
STRINGS.RECIPE_DESC.FOUNTAIN_WEREPIG = "Put that moonstone to good use!"

-----Inventors Collection
STRINGS.NAMES.WORKBENCH = "Workbench"
STRINGS.RECIPE_DESC.WORKBENCH = "For industrious types!"
STRINGS.NAMES.WORKCHAIR1 = "Workchair L"
STRINGS.RECIPE_DESC.WORKCHAIR1 = "Somewhere to sit while you work."
STRINGS.NAMES.WORKCHAIR2 = "Workchair R"
STRINGS.RECIPE_DESC.WORKCHAIR2 = "Somewhere to sit while you work."
STRINGS.NAMES.GENIUSIGN = "Do Not Disturb Sign"
STRINGS.RECIPE_DESC.GENIUSIGN = "Genius at work!"
STRINGS.NAMES.WHIRLYGISMO = "Whirly Gismo"
STRINGS.RECIPE_DESC.WHIRLYGISMO = "Watch it go!"
STRINGS.NAMES.ELECTRICTHINGAMAJIG = "Electric Thingamajig"
STRINGS.RECIPE_DESC.ELECTRICTHINGAMAJIG = "It's buzzing."
STRINGS.NAMES.METALDOOHICKY = "Metal Doohicky"
STRINGS.RECIPE_DESC.METALDOOHICKY = "Shiny."

-----Pyre Pack
STRINGS.NAMES.FIRETENT = "Coal bed"
STRINGS.RECIPE_DESC.FIRETENT = "Toasty."
STRINGS.NAMES.FIRETABLE = "Charcoal Table"
STRINGS.RECIPE_DESC.FIRETABLE = "Burnt to a crisp."
STRINGS.NAMES.BEANBAG1 = "Sack 'o' Charcoal L"
STRINGS.RECIPE_DESC.BEANBAG1 = "Chaircoal."
STRINGS.NAMES.BEANBAG2 = "Sack 'o' Charcoal R"
STRINGS.RECIPE_DESC.BEANBAG2 = "Chaircoal."
STRINGS.NAMES.BURNINGMAN = "Burning Man"
STRINGS.RECIPE_DESC.BURNINGMAN = "A safe way to let off some steam."

-----Little Girl Possessions
STRINGS.NAMES.GIRLYTENT = "Girly Tent"
STRINGS.RECIPE_DESC.GIRLYTENT = "Floral patterned!"
STRINGS.NAMES.GIRLYDISPLAY = "Butterfly Display"
STRINGS.RECIPE_DESC.GIRLYDISPLAY = "Can't fly away now, can you?"
STRINGS.NAMES.GIRLYTABLE = "Flower Table"
STRINGS.RECIPE_DESC.GIRLYTABLE = "Let nature be your table."
STRINGS.NAMES.GIRLYCHAIR1 = "Flower Chair L"
STRINGS.RECIPE_DESC.GIRLYCHAIR1 = "A chair with a pretty flower backing."
STRINGS.NAMES.GIRLYCHAIR2 = "Flower Chair R"
STRINGS.RECIPE_DESC.GIRLYCHAIR2 = "A chair with a pretty flower backing."
STRINGS.NAMES.DOLLHOUSE = "Dollhouse"
STRINGS.RECIPE_DESC.DOLLHOUSE = "The next best thing to having an actual house!"

-----Inflatables
STRINGS.NAMES.BALLOONTENT = "Balloon Tent"
STRINGS.RECIPE_DESC.BALLOONTENT = "Like a water bed, without the water."
STRINGS.NAMES.BALLOONTABLE = "Balloon Table"
STRINGS.RECIPE_DESC.BALLOONTABLE = "Let's just hope it's not too windy."
STRINGS.NAMES.BALLOONCHAIR = "Balloon Chair"
STRINGS.RECIPE_DESC.BALLOONCHAIR = "Bouncy!"
STRINGS.NAMES.BALLOONARCH = "Balloon Arch"
STRINGS.RECIPE_DESC.BALLOONARCH = "Now that's an entrance."

-----Circus Chic
STRINGS.NAMES.CIRCUSTENT = "Circus Tent"
STRINGS.RECIPE_DESC.CIRCUSTENT = "A big top, for big sleepers."
STRINGS.NAMES.CIRCUSTABLE = "Circus Table"
STRINGS.RECIPE_DESC.CIRCUSTABLE = "Let your food be the star of this show."
STRINGS.NAMES.CIRCUSCHAIR1 = "Circus Chair L"
STRINGS.RECIPE_DESC.CIRCUSCHAIR1 = "Circus chic."
STRINGS.NAMES.CIRCUSCHAIR2 = "Circus Chair R"
STRINGS.RECIPE_DESC.CIRCUSCHAIR2 = "Circus chic."
STRINGS.NAMES.CIRCUSDRAWER = "Circus Drawer"
STRINGS.RECIPE_DESC.CIRCUSDRAWER = "A comfy home for your favourite leotards."
STRINGS.NAMES.BARBELL = "Barbell"
STRINGS.RECIPE_DESC.BARBELL = "Only the strongest of survivors can lift this!"

-----Cabin Furniture
STRINGS.NAMES.CABINTENT = "Damfine Tent"
STRINGS.RECIPE_DESC.CABINTENT = "Now that's a Damfine tent!"
STRINGS.NAMES.CABINTABLE = "Cabin Table"
STRINGS.RECIPE_DESC.CABINTABLE = "Rustic and charming."
STRINGS.NAMES.CABINCHAIR1 = "Cabin Chair L"
STRINGS.RECIPE_DESC.CABINCHAIR1 = "Roughly hewn, but sturdy."
STRINGS.NAMES.CABINCHAIR2 = "Cabin Chair R"
STRINGS.RECIPE_DESC.CABINCHAIR2 = "Roughly hewn, but sturdy."
STRINGS.NAMES.CABINSHELVES = "Cabin Shelves"
STRINGS.RECIPE_DESC.CABINSHELVES = "Keep your trinkets in order."

-----Ragnarok Stock
STRINGS.NAMES.WARTENT = "War Tent"
STRINGS.RECIPE_DESC.WARTENT = "Only a little smelly."
STRINGS.NAMES.WARTABLE = "War Table"
STRINGS.RECIPE_DESC.WARTABLE = "Plan your attack!"
STRINGS.NAMES.WARCHAIR1 = "War Chair L"
STRINGS.RECIPE_DESC.WARCHAIR1 = "A chair as rigid as the warriors who sit in it."
STRINGS.NAMES.WARCHAIR2 = "War Chair R"
STRINGS.RECIPE_DESC.WARCHAIR2 = "A chair as rigid as the warriors who sit in it."
STRINGS.NAMES.PIGROAST = "Pigroast"
STRINGS.RECIPE_DESC.PIGROAST = "Something smells amazing."
STRINGS.NAMES.WEAPONSRACK = "Weapons Rack"
STRINGS.RECIPE_DESC.WEAPONSRACK = "Warrior storage."

-----Authors Abode
STRINGS.NAMES.AUTHORDESK = "Writing Desk"
STRINGS.RECIPE_DESC.AUTHORDESK = "Scratch that writing itch."
STRINGS.NAMES.AUTHORCHAIR1 = "Reading Chair L"
STRINGS.RECIPE_DESC.AUTHORCHAIR1 = "Perfect for rainy days."
STRINGS.NAMES.AUTHORCHAIR2 = "Reading Chair R"
STRINGS.RECIPE_DESC.AUTHORCHAIR2 = "Perfect for rainy days."
STRINGS.NAMES.BOOKCASE = "Bookcase"
STRINGS.RECIPE_DESC.BOOKCASE = "For book storage."

-----Spooky Hodgepodge
STRINGS.NAMES.SPIDERTENT = "Spider Tent"
STRINGS.RECIPE_DESC.SPIDERTENT = "Room for you and your creepy crawly crew."
STRINGS.NAMES.SPIDERTABLE = "Webbed Table"
STRINGS.RECIPE_DESC.SPIDERTABLE = "Care for a cup of spiders?"
STRINGS.NAMES.SPIDERCHAIR1 = "Webbed Chair L"
STRINGS.RECIPE_DESC.SPIDERCHAIR1 = "Lounging in sticky style."
STRINGS.NAMES.SPIDERCHAIR2 = "Webbed Chair R"
STRINGS.RECIPE_DESC.SPIDERCHAIR2 = "Lounging in sticky style."
STRINGS.NAMES.TOYCHEST = "Spooky Toychest"
STRINGS.RECIPE_DESC.TOYCHEST = "A spooky toychest for the creepy kiddies."

-----Steampunk
STRINGS.NAMES.GEARTENT = "Recharging station"
STRINGS.RECIPE_DESC.GEARTENT = "Rest those weary balljoints!"
STRINGS.NAMES.GEARTABLE = "Steampunk Table"
STRINGS.RECIPE_DESC.GEARTABLE = "Functionally useless, but formidably fashionable."
STRINGS.NAMES.GEARCHAIR1 = "Steampunk Chair L"
STRINGS.RECIPE_DESC.GEARCHAIR1 = "Copper comfort."
STRINGS.NAMES.GEARCHAIR2 = "Steampunk Chair R"
STRINGS.RECIPE_DESC.GEARCHAIR2 = "Copper comfort."
STRINGS.NAMES.GEARDRAWER = "Steampunk Drawers"
STRINGS.RECIPE_DESC.GEARDRAWER = "You weren't using those gears anyway."

-----Distinguished and Detested
STRINGS.NAMES.KINGLYTENT = "Kingly Tent"
STRINGS.RECIPE_DESC.KINGLYTENT = "Refined REM."
STRINGS.NAMES.KINGLYTABLE = "Kingly Table"
STRINGS.RECIPE_DESC.KINGLYTABLE = "A fancy table."
STRINGS.NAMES.KINGLYCHAIR1 = "Throne L"
STRINGS.RECIPE_DESC.KINGLYCHAIR1 = "For royal rumps."
STRINGS.NAMES.KINGLYCHAIR2 = "Throne R"
STRINGS.RECIPE_DESC.KINGLYCHAIR2 = "For royal rumps."
STRINGS.NAMES.CHESSET = "Chess Set"
STRINGS.RECIPE_DESC.CHESSET = "A game of cunning and strategy."
STRINGS.NAMES.COATRACK = "Coat Rack"
STRINGS.RECIPE_DESC.COATRACK = "Keep your coats in order."

-------------------ITEM STRINGS----------------

-----Unnamed Garden
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FOUNTAIN_WEREPIG = "I like them a whole lot better like this."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FOUNTAIN_WEREPIG = "Ha! How's it feel, big guy?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.FOUNTAIN_WEREPIG = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FOUNTAIN_WEREPIG = "This fellow makes quite the charming lawn ornament."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FOUNTAIN_WEREPIG = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.FOUNTAIN_WEREPIG = "AN UPGRADE FROM THEIR DISGUSTING MEATFORM."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FOUNTAIN_WEREPIG = "Full moon gotcha down? I hear ya, buddy."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FOUNTAIN_WEREPIG = "Scary monster is not so scary like this!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FOUNTAIN_WEREPIG = "The birds seem to like it."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FOUNTAIN_WEREPIG = "Captured in stöne and turned tö a föuntain. Eternal humiliatiön!"

-----Inventors Collection
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WORKBENCH = "Back to business!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WORKBENCH = "For building stuff."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WORKBENCH = "A table for inventor-types."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WORKBENCH = "A crude work bench, but it will do."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WORKBENCH = "Manual labor is for peasants."
STRINGS.CHARACTERS.WX78.DESCRIBE.WORKBENCH = "PRIMITIVE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WORKBENCH = "Good for workin'."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WORKBENCH = "For science-y things."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WORKBENCH = "A table for adult arts and crafts."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WORKBENCH = "I dö nöt build, I lay waste!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WORKCHAIR1 = "I'm a scientist, not a carpenter."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WORKCHAIR1 = "It's alright"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WORKCHAIR1 = "A chair."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WORKCHAIR1 = "It suffices."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WORKCHAIR1 = "Well, it's a chair."
STRINGS.CHARACTERS.WX78.DESCRIBE.WORKCHAIR1 = "ORGANIC CHAIR."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WORKCHAIR1 = "It's nice."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WORKCHAIR1 = "Would not hold my mighty weight!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WORKCHAIR1 = "It's a chair!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WORKCHAIR1 = "A chair!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WORKCHAIR2 = "I'm a scientist, not a carpenter."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WORKCHAIR2 = "It's alright"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WORKCHAIR2 = "A chair."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WORKCHAIR2 = "It suffices."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WORKCHAIR2 = "Well, it's a chair."
STRINGS.CHARACTERS.WX78.DESCRIBE.WORKCHAIR2 = "ORGANIC CHAIR."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WORKCHAIR2 = "It's nice."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WORKCHAIR2 = "Would not hold my mighty weight!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WORKCHAIR2 = "It's a chair!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WORKCHAIR2 = "A chair!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GENIUSIGN = "I wouldn't want to be interrupted when inspiration strikes."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GENIUSIGN = "Humble."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GENIUSIGN = "All work and no play..."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GENIUSIGN = "*Scoff*"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GENIUSIGN = "'Idiot at play.'"
STRINGS.CHARACTERS.WX78.DESCRIBE.GENIUSIGN = "A DISPLAY OF SELF-IMPORTANCE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GENIUSIGN = "Guess he's busy."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GENIUSIGN = "Tiny man is building things?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GENIUSIGN = "Mr. Higgsbury sure is smart!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GENIUSIGN = "The scientist tinkers!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHIRLYGISMO = "My latest invention!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WHIRLYGISMO = "What the heck is that?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WHIRLYGISMO = "..."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WHIRLYGISMO = "Mechanical frivolousness."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WHIRLYGISMO = "A trivial trinket."
STRINGS.CHARACTERS.WX78.DESCRIBE.WHIRLYGISMO = "POINTLESS."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WHIRLYGISMO = "Sure is... somethin'."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WHIRLYGISMO = "Tiny mans toy."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WHIRLYGISMO = "What's it do?"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WHIRLYGISMO = "I see nö pöint."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ELECTRICTHINGAMAJIG = "Fascinating."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ELECTRICTHINGAMAJIG = "Is it supposed to do something?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.ELECTRICTHINGAMAJIG = "Like life, I struggle to find it's purpose."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ELECTRICTHINGAMAJIG = "What am I to make of this?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ELECTRICTHINGAMAJIG = "Useless."
STRINGS.CHARACTERS.WX78.DESCRIBE.ELECTRICTHINGAMAJIG = "IT'S VAGUELY ELECTRICAL."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ELECTRICTHINGAMAJIG = "..."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ELECTRICTHINGAMAJIG = "Is... thing."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ELECTRICTHINGAMAJIG = "Mr. Higgsbury makes all kinds of things like this."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ELECTRICTHINGAMAJIG = "Wilsön öf Higgsbury is quite fönd öf his scrap metal!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.METALDOOHICKY = "How useful!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.METALDOOHICKY = "Uh?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.METALDOOHICKY = "Hm."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.METALDOOHICKY = "..."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.METALDOOHICKY = "Pointless."
STRINGS.CHARACTERS.WX78.DESCRIBE.METALDOOHICKY = "CAN I EAT IT?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.METALDOOHICKY = "Not sure what to make of this."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.METALDOOHICKY = "??"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.METALDOOHICKY = "We wonder what this is."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.METALDOOHICKY = "Metal litter!"

-----Pyre Pack

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIRETENT = "It's quite hot in there."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FIRETENT = "It's perfect!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.FIRETENT = "It's embers will burn through the night."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FIRETENT = "That's a fire hazard."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FIRETENT = "I'd rather not sleep in soot and rags like an orphan."
STRINGS.CHARACTERS.WX78.DESCRIBE.FIRETENT = "CIRCUITS OVERHEATING."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FIRETENT = "Seems like a waste of good wood."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FIRETENT = "Skin is not so mighty as muscles. Burn easy."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FIRETENT = "That doesn't look too cozy."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FIRETENT = "Sleeping here will be a true test öf endurance."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIRETABLE = "Table-shaped charcoal."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FIRETABLE = "Isn't it beautiful?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.FIRETABLE = "A shadow of it's former self. Just like me."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FIRETABLE = "Burned, through and through."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FIRETABLE = "The burnt husk of a table."
STRINGS.CHARACTERS.WX78.DESCRIBE.FIRETABLE = "SERVES IT RIGHT."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FIRETABLE = "That was probably a nice wooden table, once."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FIRETABLE = "It gets fire dust in my food!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FIRETABLE = "It gets our fur all sooty!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FIRETABLE = "Fröm the flames, it will carry ön."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEANBAG1 = "Soot isn't great for my lungs."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEANBAG1 = "I've always wanted one of these!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEANBAG1 = "Abigail, has this left a black mark on my skirt?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEANBAG1 = "We had quite a few of these in the kids corner at the library."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEANBAG1 = "I don't want to get soot on my suit."
STRINGS.CHARACTERS.WX78.DESCRIBE.BEANBAG1 = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEANBAG1 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEANBAG1 = "Is bag of coal."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEANBAG1 = "Crunchy!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEANBAG1 = "Ack! It pulls me in! Is this a trap?!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEANBAG2 = "Soot isn't great for my lungs."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEANBAG2 = "I've always wanted one of these!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEANBAG2 = "Abigail, has this left a black mark on my skirt?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEANBAG2 = "We had quite a few of these in the kids corner at the library."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEANBAG2 = "I don't want to get soot on my suit."
STRINGS.CHARACTERS.WX78.DESCRIBE.BEANBAG2 = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEANBAG2 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEANBAG2 = "Is bag of coal."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEANBAG2 = "Crunchy!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEANBAG2 = "Ack! It pulls me in! Is this a trap?!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "Need a light, 'pal'?",
					OUT = "At least I can start it up again.",
					EMBERS = "I should put something on the fire before it goes out.",
					LOW = "The fire's getting a bit low.",
					NORMAL = "This is my best invention yet.",
					HIGH = "Let's see how much you like smoking now!",
				}
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "Now that's a face I'd like to set on fire.",
					OUT = "Aww, funs over.",
					EMBERS = "Uh oh. It's almost gone!",
					LOW = "This fire is small and boring.",
					NORMAL = "That's more like it!",
					HIGH = "BURN! BURN FASTER!",
				}
STRINGS.CHARACTERS.WENDY.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "A magician burns the same as a witch upon a pyre.",
					OUT = "That was fun while it lasted.",
					EMBERS = "The fire is on the verge of death.",
					LOW = "Fires of vengeance should burn hotter than this.",
					NORMAL = "Just a taste of the fires that await him in death.",
					HIGH = "The roaring fires of hell!",
				}
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "A shrine of a different kind.",
					OUT = "I can re-light it.",
					EMBERS = "The fire has almost self-extinguished.",
					LOW = "From a little spark may burst a flame.",
					NORMAL = "It's a bit juvenile, but oddly satisfying.",
					HIGH = "A blazing inferno!",
				}
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "That ungrateful wretch.",
					OUT = "It's gone cold.",
					EMBERS = "I should attend to that.",
					LOW = "Got a light?",
					NORMAL = "Chin up, old boy.",
					HIGH = "Better him than me.",
				}
STRINGS.CHARACTERS.WX78.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "INPUT: BURNABLES. OUTPUT: FUN.",
					OUT = "NO FIRE DETECTED",
					EMBERS = "WARNING: FIRE LEVELS CRITICAL",
					LOW = "WARNING: FIRE LEVELS LOW",
					NORMAL = "THIS IS A HOBBY I CAN GET BEHIND.",
					HIGH = "I LOVE THE SMELL OF BURNING ORGANICS IN THE MORNING.",
				}
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "Looks like the perfect place to light a fire.",
					OUT = "If only I had some wood.",
					EMBERS = "I should go chop some wood for that, eh?",
					LOW = "There should be some wood around here somewhere.",
					NORMAL = "Set ablaze.",
					HIGH = "A whole lotta fire for a whole lotta hoser.",
				}
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "Fragile man was like twig before. Is even more so now!",
					OUT = "Uh oh. It turned off.",
					EMBERS = "Needs more little sticks!",
					LOW = "The fire is not hot enough.",
					NORMAL = "Fragile man go up in flames!",
					HIGH = "HAHA! Stickman Maxwell is good kindling!",
				}
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "This isn't some kind of voodoo thing, right?",
					OUT = "Well, that's done. But not forever!",
					EMBERS = "We should put something on the fire before it goes out.",
					LOW = "The fire's getting a touch low.",
					NORMAL = "The toastiest of fires.",
					HIGH = "That fire is huge!",
				}
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "Tis nöt a Vikings funeral I have planned för yöu, Shadöw King.",
					OUT = "And the light flickers öut.",
					EMBERS = "The fire's nearly dead.",
					LOW = "The fire's slöwly dying.",
					NORMAL = "Amidst hellfire, as he shöuld be!",
					HIGH = "Like my anger, the fire röars!",
				}
STRINGS.CHARACTERS.WINONA.DESCRIBE.BURNINGMAN  =
				{
				    GENERIC = "A very powerful firepit.",
					OUT = "My sister was afraid of the dark.",
					EMBERS = "On its last legs.",
					LOW = "It's gonna go out soon",
					NORMAL = "This one's for Charlie.",
					HIGH = "Properly roaring.",
				}

-----Little Girl Possessions

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GIRLYTENT = "A small tent with pressed flowers."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GIRLYTENT = "It's cute, I guess."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GIRLYTENT = "It speaks to my soul."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GIRLYTENT = "Decorated with the various flora found here in The Constant."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GIRLYTENT = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.GIRLYTENT = "REVOLTINGLY ADORABLE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GIRLYTENT = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GIRLYTENT = "Tent with teeny flowers on it."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GIRLYTENT = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GIRLYTENT = "A tent suited tö a fair maiden."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GIRLYTABLE = "Now that's what I call flower power!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GIRLYTABLE = "That's a big flower."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GIRLYTABLE = "Delicate, yet standing firm. Much like myself."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GIRLYTABLE = "An Anemone Coronaria grown to an unnatural height."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GIRLYTABLE = "There's only one flower for me."
STRINGS.CHARACTERS.WX78.DESCRIBE.GIRLYTABLE = "THIS TABLE IS MADE OF PLANTMATTER. I HATE IT."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GIRLYTABLE = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GIRLYTABLE = "Is pretty flower table!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GIRLYTABLE = "This table smells great!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GIRLYTABLE = "This table is nöt befitting öf a warriör!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GIRLYDISPLAY = "What finely pinned specimen!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GIRLYDISPLAY = "Kinda creepy."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GIRLYDISPLAY = "Their beauty is eternally captured."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GIRLYDISPLAY = "Young Wendy could be quite the entomologist."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GIRLYDISPLAY = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.GIRLYDISPLAY = "IMPRISONED FOR LIFE. AND DEATH."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GIRLYDISPLAY = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GIRLYDISPLAY = "Little flutterbys is so still now!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GIRLYDISPLAY = "Bye bye, butterfly."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GIRLYDISPLAY = "Tröphies cöllected fröm the Deadwaker's hunts!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GIRLYCHAIR1 = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GIRLYCHAIR1 = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.GIRLYCHAIR1 = "How pretty."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GIRLYCHAIR1 = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GIRLYCHAIR1 = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.GIRLYCHAIR1 = "'FLOWERS' ARE NOT THE FIRST THING I ASSOCIATE WITH STRUCTURAL INTEGRITY."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GIRLYCHAIR1 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GIRLYCHAIR1 = "Flowers are little and weak. Flower chair is the same!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GIRLYCHAIR1 = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GIRLYCHAIR1 = "A dainty chair."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GIRLYCHAIR2 = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GIRLYCHAIR2 = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.GIRLYCHAIR2 = "How pretty."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GIRLYCHAIR2 = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GIRLYCHAIR2 = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.GIRLYCHAIR2 = "'FLOWERS' ARE NOT THE FIRST THING I ASSOCIATE WITH STRUCTURAL INTEGRITY."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GIRLYCHAIR2 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GIRLYCHAIR2 = "Flowers are little and weak. Flower chair is the same!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GIRLYCHAIR2 = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GIRLYCHAIR2 = "A dainty chair."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOLLHOUSE = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DOLLHOUSE = "I like houses better when they're burning."
STRINGS.CHARACTERS.WENDY.DESCRIBE.DOLLHOUSE = "'I'm leaving you,' she told Ken. And oh, the heartbreak."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DOLLHOUSE = "Wendy has given those delightful little gnomes a piece of prime real estate."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DOLLHOUSE = "This feels strangely familiar."
STRINGS.CHARACTERS.WX78.DESCRIBE.DOLLHOUSE = "BEG FOR YOUR PUNY LIVES."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DOLLHOUSE = "Bite-sized."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DOLLHOUSE = "Tiny house for tiny peoples."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DOLLHOUSE = "Wendy showed us how to play 'Mary Maloney's Dinner Party'! It was... kinda gruesome."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DOLLHOUSE = "A warriör has nö time tö play döllies!"

-----Inflatables
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLOONTENT = "Well... A few bounces before bed couldn't hurt. As long as no one sees."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BALLOONTENT = "Wahoo!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BALLOONTENT = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BALLOONTENT = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BALLOONTENT = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.BALLOONTENT = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BALLOONTENT = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BALLOONTENT = "Is bouncy house!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BALLOONTENT = "Whee!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BALLOONTENT = "This is nö place för a spear such as mine."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLOONTABLE = "Impressive, if not really functional."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BALLOONTABLE = "Don't let it float away!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BALLOONTABLE = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BALLOONTABLE = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BALLOONTABLE = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.BALLOONTABLE = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BALLOONTABLE = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BALLOONTABLE = "Squeaky table."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BALLOONTABLE = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BALLOONTABLE = "Ballöön sörcery!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLOONCHAIR = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BALLOONCHAIR = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.BALLOONCHAIR = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BALLOONCHAIR = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BALLOONCHAIR = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.BALLOONCHAIR = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BALLOONCHAIR = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BALLOONCHAIR = "Do not want to pop chair and make scary loud noise."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BALLOONCHAIR = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BALLOONCHAIR = "It can önly höld the weight öf the featherlight mime."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BALLOONARCH = "Where is he getting all these balloons from?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BALLOONARCH = "Wow!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BALLOONARCH = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BALLOONARCH = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BALLOONARCH = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.BALLOONARCH = "WORLD'S WORST RAINBOW."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BALLOONARCH = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BALLOONARCH = "My favourite colours!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BALLOONARCH = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BALLOONARCH = "A grand entrance!"

-----Circus Chic

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CIRCUSTENT = "What I would give for a bag of roasted peanuts right about now."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CIRCUSTENT = "I'm gonna be a fire-eater!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CIRCUSTENT = "Cotton candy isn't the healthiest bedtime snack, but arguably the fluffiest."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CIRCUSTENT = "A circus in the middle of the woods! Delightfully absurd."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CIRCUSTENT = "This place feels like enough of a circus without pitching tents like this."
STRINGS.CHARACTERS.WX78.DESCRIBE.CIRCUSTENT = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CIRCUSTENT = "Never been a fan of the circus. Last thing I need is to be some kinda sideshow."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CIRCUSTENT = "Feels like home!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CIRCUSTENT = "We went to the circus once."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CIRCUSTENT = "I löve a gööd perfömance."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CIRCUSTABLE = "A table to make the Ringling Brothers proud."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CIRCUSTABLE = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.CIRCUSTABLE = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CIRCUSTABLE = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CIRCUSTABLE = "I consider myself a ringleader of sorts, but this just looks tacky."
STRINGS.CHARACTERS.WX78.DESCRIBE.CIRCUSTABLE = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CIRCUSTABLE = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CIRCUSTABLE = "Wolfgang can be star of show again!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CIRCUSTABLE = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CIRCUSTABLE = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CIRCUSCHAIR1 = "Quite a fanciful piece of furniture."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CIRCUSCHAIR1 = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.CIRCUSCHAIR1 = "A seat fit for merrymaking. I am not much of a merrymaker."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CIRCUSCHAIR1 = "A jubilant chair."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CIRCUSCHAIR1 = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.CIRCUSCHAIR1 = "GAUDY VAUDEVILLE AESTHETICS DETECTED."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CIRCUSCHAIR1 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CIRCUSCHAIR1 = "Is strongest and bestest of chairs!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CIRCUSCHAIR1 = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CIRCUSCHAIR1 = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CIRCUSCHAIR2 = "Quite a fanciful piece of furniture."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CIRCUSCHAIR2 = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.CIRCUSCHAIR2 = "A seat fit for merrymaking. I am not much of a merrymaker."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CIRCUSCHAIR2 = "A jubilant chair."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CIRCUSCHAIR2 = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.CIRCUSCHAIR2 = "GAUDY VAUDEVILLE AESTHETICS DETECTED."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CIRCUSCHAIR2 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CIRCUSCHAIR2 = "Is strongest and bestest of chairs!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CIRCUSCHAIR2 = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CIRCUSCHAIR2 = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CIRCUSDRAWER = "Always been a fan of stripes, myself."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CIRCUSDRAWER = "Big and old! Just like Wolfgang, hehehe."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CIRCUSDRAWER = "I wonder if I could fit in there."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CIRCUSDRAWER = "A vintage set of chestdrawers."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CIRCUSDRAWER = "Are there a dozen clowns hiding in here?"
STRINGS.CHARACTERS.WX78.DESCRIBE.CIRCUSDRAWER = "HIDEOUS SIDESHOW FURNITURE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CIRCUSDRAWER = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CIRCUSDRAWER = "Is broad and mighty chest, just like mine!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CIRCUSDRAWER = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CIRCUSDRAWER = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BARBELL = "There's no way I won't kill myself trying to pick this up."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BARBELL = "Too...heavy...!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BARBELL = "That's quite large."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BARBELL = "With my back?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BARBELL = "Tch. I'd rather astound with tricks of the mind, thank you."
STRINGS.CHARACTERS.WX78.DESCRIBE.BARBELL = "WEIGHT OVERLOAD."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BARBELL = "Don't think I'll be liftin' that any time soon, eh?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BARBELL = "Hah! Is nothing for my mighty arms!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BARBELL = "Wow, Mr. Wolfgang is so strong!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BARBELL = "One day I'll be able tö lift that över my head and thröw it! But töday is nöt that day."

-----Cabin Furniture

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CABINTENT = "Looks like a stick-y situation."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CABINTENT = "Looks like a heap of matchwood to me."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CABINTENT = "It'll keep the rain off. For a while."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CABINTENT = "I'd rather curl up with a good book."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CABINTENT = "This will barely suit my needs."
STRINGS.CHARACTERS.WX78.DESCRIBE.CABINTENT = "BETTER THAN NOTHING."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CABINTENT = "Wood ya look at that."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CABINTENT = "Is house of toothpicks."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CABINTENT = "Just like the time we built a house out of popsicle sticks!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CABINTENT = "I'll huff, and I'll puff...!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CABINTABLE = "Roughly hewn, but sturdy."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CABINTABLE = "It'd look nicer if it was on fire."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CABINTABLE = "I understand, table. A piece of me is missing too."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CABINTABLE = "Better to have tree rings than coffee rings."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CABINTABLE = "How...quaint..."
STRINGS.CHARACTERS.WX78.DESCRIBE.CABINTABLE = "IT STANDS. THAT'S SOMETHING. I GUESS."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CABINTABLE = "Ain't that a beaut."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CABINTABLE = "Is table!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CABINTABLE = "It would be nice to eat at a table again."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CABINTABLE = "Fallen wööden föes, put tö gööd use!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CABINCHAIR1 = "I won't have to sit in the dirt!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CABINCHAIR1 = "A chair, for my butt."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CABINCHAIR1 = "To sit and ponder death."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CABINCHAIR1 = "Rather firm, but it suffices."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CABINCHAIR1 = "Only marginally better than being shackled to a throne."
STRINGS.CHARACTERS.WX78.DESCRIBE.CABINCHAIR1 = "A CHAIR, MADE FROM ORGANIC MATERIAL."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CABINCHAIR1 = "Comfy as can be."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CABINCHAIR1 = "This could not hold my mighty weight!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CABINCHAIR1 = "Is this seat taken?"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CABINCHAIR1 = "A warrior does not sit until her last enemy has fallen!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CABINCHAIR2 = "I won't have to sit in the dirt!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CABINCHAIR2 = "A chair, for my butt."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CABINCHAIR2 = "To sit and ponder death."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CABINCHAIR2 = "Rather firm, but it suffices."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CABINCHAIR2 = "Only marginally better than being shackled to a throne."
STRINGS.CHARACTERS.WX78.DESCRIBE.CABINCHAIR2 = "A CHAIR, MADE FROM ORGANIC MATERIAL."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CABINCHAIR2 = "Comfy as can be."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CABINCHAIR2 = "This could not hold my mighty weight!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CABINCHAIR2 = "Is this seat taken?"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CABINCHAIR2 = "A warrior does not sit until her last enemy has fallen!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CABINSHELVES = "Hopefully it doesn't collapse."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CABINSHELVES = "I won't burn this one. Scouts honor!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CABINSHELVES = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CABINSHELVES = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CABINSHELVES = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.CABINSHELVES = "A VASTLY INFERIOR SHELVING UNIT."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CABINSHELVES = "For all those little knick-knacks I keep pickin' up."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CABINSHELVES = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CABINSHELVES = "Ms. Wickerbottom says we'll hurt ourselves if we try and climb it."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CABINSHELVES = "Tö the victör gö the spöils. And the spöils gö tö the shelf!"

-----Ragnarok Stock

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WARTENT = "Smells like beefalo."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WARTENT = "Ewww! It's smelly!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WARTENT = "Furry and funky."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WARTENT = "Offensive to the olfactories."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WARTENT = "I'm already living like an animal, I don't need to smell like one too."
STRINGS.CHARACTERS.WX78.DESCRIBE.WARTENT = "A SKIN PRISON."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WARTENT = "Beats the ground."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WARTENT = "Will wake with hairball."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WARTENT = "Stinky, but warm!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WARTENT = "Swaddled in the flesh öf my föes!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WARTABLE = "An unyielding table."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WARTABLE = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.WARTABLE = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WARTABLE = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WARTABLE = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.WARTABLE = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WARTABLE = "A sturdy lookin' table."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WARTABLE = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WARTABLE = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WARTABLE = "Sölid and uncömprömising, like yöurs truly."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WARCHAIR1 = "That's one way to keep your spine straight."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WARCHAIR1 = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.WARCHAIR1 = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WARCHAIR1 = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WARCHAIR1 = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.WARCHAIR1 = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WARCHAIR1 = "There's some kinda engraving in the wood."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WARCHAIR1 = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WARCHAIR1 = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WARCHAIR1 = "A chair after my öwn heart!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WARCHAIR2 = "That's one way to keep your spine straight."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WARCHAIR2 = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.WARCHAIR2 = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WARCHAIR2 = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WARCHAIR2 = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.WARCHAIR2 = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WARCHAIR2 = "There's some kinda engraving in the wood."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WARCHAIR2 = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WARCHAIR2 = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WARCHAIR2 = "A chair after my öwn heart!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGROAST = "I'm so tired of carrots. But they're bipedal... though, they *are* pigs. But they speak..."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGROAST = "Luau!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGROAST = "Crackling flesh and dripping fat could awaken a primal hunger in anyone."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGROAST = "Moral quandaries aside, this will be a veritable feast."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PIGROAST = "Primitive, but delicious."
STRINGS.CHARACTERS.WX78.DESCRIBE.PIGROAST = "A MEATLING PUT IN IT'S PLACE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PIGROAST = "Sorry, fella. But you're gonna be tasty."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PIGROAST = "Friend is food."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PIGROAST = "You'll leave us alone now, won't you, you mean old pig?"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGROAST = "Yöur snackrifice will nöt be in vain, fallen öne!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WEAPONSRACK = "A place to store weapons."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WEAPONSRACK = "This is where we keep all the sharp and stabby things!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WEAPONSRACK = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WEAPONSRACK = "No better defense than a good offense."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WEAPONSRACK = "I prefer weapons of the intangible sort."
STRINGS.CHARACTERS.WX78.DESCRIBE.WEAPONSRACK = "DEATHRACK."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WEAPONSRACK = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WEAPONSRACK = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WEAPONSRACK = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WEAPONSRACK = "Tö arms!"

-----Authors Abode

STRINGS.CHARACTERS.GENERIC.DESCRIBE.AUTHORDESK = "I can take notes here."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.AUTHORDESK = "Ugh, I never liked note-taking in school."
STRINGS.CHARACTERS.WENDY.DESCRIBE.AUTHORDESK = "That's a pretty flower. Surrounded by thorny agony."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.AUTHORDESK = "Excellent for some night-time writing."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.AUTHORDESK = "I read books, not write them."
STRINGS.CHARACTERS.WX78.DESCRIBE.AUTHORDESK = "IT'S TIME TO GET MY PLANS TO DESTROY ALL ORGANIC LIFE ON PAPER."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.AUTHORDESK = "For writer types."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.AUTHORDESK = "Am not so good with writing."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.AUTHORDESK = "Let's draw!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.AUTHORDESK = "It is the swörd that is mightier than the pen!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.AUTHORCHAIR1 = "Kind of itchy."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.AUTHORCHAIR1 = "It'd go up in a flash. Fwoom!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.AUTHORCHAIR1 = "We had chairs like this at the local library. They only smelled marginally better."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.AUTHORCHAIR1 = "Impeccably crafted."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.AUTHORCHAIR1 = "About as comfortable as it looks."
STRINGS.CHARACTERS.WX78.DESCRIBE.AUTHORCHAIR1 = "FUNCTION: SITTING."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.AUTHORCHAIR1 = "Ol' Grandma Splinters sat in a chair like this."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.AUTHORCHAIR1 = "My arms never need to rest!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.AUTHORCHAIR1 = "Father had a chair like this..."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.AUTHORCHAIR1 = "Smells a little like beefalö."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.AUTHORCHAIR2 = "Kind of itchy."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.AUTHORCHAIR2 = "It'd go up in a flash. Fwoom!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.AUTHORCHAIR2 = "We had chairs like this at the local library. They only smelled marginally better."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.AUTHORCHAIR2 = "Impeccably crafted."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.AUTHORCHAIR2 = "About as comfortable as it looks."
STRINGS.CHARACTERS.WX78.DESCRIBE.AUTHORCHAIR2 = "FUNCTION: SITTING."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.AUTHORCHAIR2 = "Ol' Grandma Splinters sat in a chair like this."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.AUTHORCHAIR2 = "My arms never need to rest!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.AUTHORCHAIR2 = "Father had a chair like this..."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.AUTHORCHAIR2 = "Smells a little like beefalö."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOKCASE = "For book storage!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BOOKCASE = "For readin' types."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BOOKCASE = "I'm fond of Grimm's Fairy Tales, myself."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BOOKCASE = "Oh, my eyes are misting up."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BOOKCASE = "There's only one book I need."
STRINGS.CHARACTERS.WX78.DESCRIBE.BOOKCASE = "DATA STORAGE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BOOKCASE = "For readin' types."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BOOKCASE = "Is as big as me!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BOOKCASE = "We hope Ms. Wickerbottom will read us a bedtime story."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BOOKCASE = "Tö höld the störies they will tell öf my battles."

-----Spooky Hodgepodge

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDERTENT = "I am *not* going in there."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPIDERTENT = "Kill it with fire!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPIDERTENT = "Spiders are not too fond of Abigail."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPIDERTENT = "If I wasn't sleeping before, I definitely won't be now."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPIDERTENT = "Yeugh."
STRINGS.CHARACTERS.WX78.DESCRIBE.SPIDERTENT = "THE WEBBING GUNKS UP MY BALLJOINTS."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPIDERTENT = "That's the stuff of nightmares."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPIDERTENT = "No! No! Do not make Wolfgang sleep here!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPIDERTENT = "Lets have a sleepover with all our friends!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPIDERTENT = "This is a place för battle, nöt för slumber!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDERTABLE = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPIDERTABLE = "Yuck! It's all sticky!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPIDERTABLE = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPIDERTABLE = "I'm not entirely sure this is hygenic."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPIDERTABLE = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.SPIDERTABLE = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPIDERTABLE = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPIDERTABLE = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPIDERTABLE = "Mother always said to use a table cloth in polite company."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPIDERTABLE = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDERCHAIR1 = "That's a web I wouldn't mind getting caught in."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPIDERCHAIR1 = "Good for lounging around."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPIDERCHAIR1 = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPIDERCHAIR1 = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPIDERCHAIR1 = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.SPIDERCHAIR1 = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPIDERCHAIR1 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPIDERCHAIR1 = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPIDERCHAIR1 = "It reminds us of the beach! We liked the beach."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPIDERCHAIR1 = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDERCHAIR2 = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPIDERCHAIR2 = "Good for lounging around."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPIDERCHAIR2 = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPIDERCHAIR2 = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPIDERCHAIR2 = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.SPIDERCHAIR2 = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPIDERCHAIR2 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPIDERCHAIR2 = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPIDERCHAIR2 = "It reminds us of the beach! We liked the beach."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPIDERCHAIR2 = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOYCHEST = "Looks a little dusty."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TOYCHEST = "Yeuck, cobwebs!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TOYCHEST = "A place for playthings."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOYCHEST = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TOYCHEST = "I'm far too old to be playing with toys."
STRINGS.CHARACTERS.WX78.DESCRIBE.TOYCHEST = "WHERE MY SMALL ROBOT BRETHREN ARE HELD CAPTIVE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TOYCHEST = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TOYCHEST = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TOYCHEST = "So many toys to play with!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TOYCHEST = ""

-----Steampunk

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GEARTENT = "Looks a bit, er, cramped?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GEARTENT = "Why is this giving me such a bad feeling?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.GEARTENT = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GEARTENT = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GEARTENT = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.GEARTENT = "FINALLY. CIVILITY."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GEARTENT = "Metal's not the comfiest to sleep on."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GEARTENT = "Wolfgang does not like small spaces!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GEARTENT = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GEARTENT = "This gives me the heebie-jeebies."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GEARTABLE = "I could be using those gears to build something incredible!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GEARTABLE = "Fireproof! Rats."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GEARTABLE = "Aren't gears supposed to do something?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GEARTABLE = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GEARTABLE = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.GEARTABLE = "STYLISH."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GEARTABLE = "I like a table I can really sink my teeth into."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GEARTABLE = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GEARTABLE = "This table reminds us of the plumbing under the sink back home!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GEARTABLE = "Where did these pipes come from?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GEARCHAIR1 = "Looks like something an evil genius would like. I'm moreso just a genius."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GEARCHAIR1 = "Doesn't look too flammable."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GEARCHAIR1 = "It reeks of machine oil and leather."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GEARCHAIR1 = "An interesting use of gears and metal."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GEARCHAIR1 = "How gauche."
STRINGS.CHARACTERS.WX78.DESCRIBE.GEARCHAIR1 = "SATISFACTORY."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GEARCHAIR1 = "Looks a bit like a car seat."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GEARCHAIR1 = "."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GEARCHAIR1 = "."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GEARCHAIR1 = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GEARCHAIR2 = "Looks like something an evil genius would like. I'm moreso just a genius."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GEARCHAIR2 = "Doesn't look too flammable."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GEARCHAIR2 = "It reeks of machine oil and leather."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GEARCHAIR2 = "An interesting use of gears and metal."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GEARCHAIR2 = "How gauche."
STRINGS.CHARACTERS.WX78.DESCRIBE.GEARCHAIR2 = "SATISFACTORY."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GEARCHAIR2 = "Looks a bit like a car seat."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GEARCHAIR2 = "."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GEARCHAIR2 = "."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GEARCHAIR2 = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GEARDRAWER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GEARDRAWER = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.GEARDRAWER = "."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GEARDRAWER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GEARDRAWER = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.GEARDRAWER = "FORM AND FUNCTION."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GEARDRAWER = "Not too keen on metal."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GEARDRAWER = "."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GEARDRAWER = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GEARDRAWER = "."

-----Distinguished and Detested

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KINGLYTENT = "Marble isn't known for being particularly comfortable."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.KINGLYTENT = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.KINGLYTENT = "It feels more like being encased in a tomb."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KINGLYTENT = "A bit ostentatious."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KINGLYTENT = "No more sleeping in the dirt like a dog."
STRINGS.CHARACTERS.WX78.DESCRIBE.KINGLYTENT = "DISGUSTINGLY ORNATE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.KINGLYTENT = "I'm a simple guy. This isn't too simple."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KINGLYTENT = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.KINGLYTENT = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KINGLYTENT = "This is a King's tent, and I'm more of a Knight."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KINGLYTABLE = "Who needs a solid marble table?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.KINGLYTABLE = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.KINGLYTABLE = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KINGLYTABLE = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KINGLYTABLE = "I've outdone myself."
STRINGS.CHARACTERS.WX78.DESCRIBE.KINGLYTABLE = "LIKE MOST THINGS, THIS MATERIAL IS INFERIOR TO METAL."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.KINGLYTABLE = "Feh."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KINGLYTABLE = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.KINGLYTABLE = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KINGLYTABLE = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KINGLYCHAIR1 = "A seat for hoity-toity types."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.KINGLYCHAIR1 = "For the pain-in-the-butt's butt."
STRINGS.CHARACTERS.WENDY.DESCRIBE.KINGLYCHAIR1 = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KINGLYCHAIR1 = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KINGLYCHAIR1 = "Fit for a king, without the shackles."
STRINGS.CHARACTERS.WX78.DESCRIBE.KINGLYCHAIR1 = "Pink's not really my colour."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.KINGLYCHAIR1 = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KINGLYCHAIR1 = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.KINGLYCHAIR1 = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KINGLYCHAIR1 = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KINGLYCHAIR2 = "A seat for hoity-toity types."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.KINGLYCHAIR2 = "For the pain-in-the-butt's butt."
STRINGS.CHARACTERS.WENDY.DESCRIBE.KINGLYCHAIR2 = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KINGLYCHAIR2 = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KINGLYCHAIR2 = "Fit for a king, without the shackles."
STRINGS.CHARACTERS.WX78.DESCRIBE.KINGLYCHAIR2 = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.KINGLYCHAIR2 = "Pink's not really my colour."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KINGLYCHAIR2 = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.KINGLYCHAIR2 = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KINGLYCHAIR2 = ""

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHESSET = "I'll never look at one of these the same way again."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CHESSET = "Dumb game."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CHESSET = "I'd rather not."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHESSET = "How I used to love this game..."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CHESSET = "Checkmate."
STRINGS.CHARACTERS.WX78.DESCRIBE.CHESSET = "FLESHLINGS ARE SO OBSESSED WITH WASTING WHAT LITTLE TIME THEY HAVE."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CHESSET = "Not sure I know the rules, ey?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CHESSET = "Hah! I make tiny pieces dance!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CHESSET = "It seems too complicated for us."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CHESSET = "Bah!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.COATRACK = "A place to hang my hat."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COATRACK = "Guess I'll stop leaving my raincoat wherever it lands."
STRINGS.CHARACTERS.WENDY.DESCRIBE.COATRACK = "Good for hanging."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COATRACK = "A place for everything and everything in its place."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COATRACK = "Good to keep the dust off my coattails."
STRINGS.CHARACTERS.WX78.DESCRIBE.COATRACK = "I WILL KEEP MY METAL CHASSIS WHERE IT IS, THANKS."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COATRACK = "Where'd that hoser get varnish all the way out here?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COATRACK = "Could snap like twig between my mighty fingers."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COATRACK = "If we could take off our coat, this is where it would go."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COATRACK = "I'd hang my helm, if it wasn't shameful för a warriör tö be seen withöut öne."